impact/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('webapp.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

impct/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from .views import (index_view,
                    about_view,
                    contacts_view)

app_name = 'webapp'
urlpatterns = [
    path(r'', index_view, name='home'),
    path(r'about/', about_view, name='about'),
    path(r'contacts/', contacts_view, name='contacts'),
]

webapp/models.py
from django.db import models


class Site(models.Model):
    details = models.CharField(default="Starts", max_length=20)

    def __str__(self):
        return self.details

webapp/views.py
from django.shortcuts import render

from .models import Site


def index_view(request):
    details = Site.objects.all()

    context = {
        "title": "Home",
        "details": details,
    }

    return render(request, "webapp/index.html", context)


def about_view(request):
    context = {
        "title": "About"
    }

    return render(request, "webapp/about.html", context)


def contacts_view(request):
    context = {
        "title": "Contacts"
    }

    return render(request, "webapp/contacts.html", context)

templates/webapp/about.html
{% extends 'webapp/base_layout.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
    <div class="about row" style='background-image: url("{% static 'webapp/images/about.png' %}")'>
        <div class="col-sm-3">
            <h3 class="font-weight-bold">ABOUT US</h3>
            <p>We are an idea driven and result oriented agency built to connect brands and experiences. Our niche in
                event management, brand building, content creation, talent sourcing, branding and merchandising has
                etched our name in the communication industry.</p>
        </div>
    </div>
    <div class="about-2">
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'webapp/images/avril.png' %}" class="img-fluid" alt="">
            </div>
            <div class="col-md-6">
                <div class="vsn-msn" id="vision">
                    <h3>Our Vision</h3>
                    <p>To be the leading promotion and positioning consultants within East Africa. To be acknowledged
                        for distinguished service to every client we encounter and every project we undertake.</p>
                </div>
                <div class="vsn-msn" id="mission">
                    <h3>Our Mission</h3>
                    <p>To provide our clients with quality services that improve their bottom line and increase their
                        brand worth.</p>
                </div>
            </div>
        </div>
    </div>
    <!-- philosophy -->
    <div class="philosophy">
        <div class="row">
            <div class="col-md-6 order-md-1">
                <img src="{% static 'webapp/images/impact-3.png' %}" class="img-fluid" alt="">
            </div>
            <div class="col-md-6 order-md-0">
                <div>
                    <h2>OUR PHILOSOPHY</h2>
                    <p>We aim to inspire generations and contribute to a sense of global community with products
                        that captivate and educate.</p>
                    <p>Our philosophy is simple: we take brands through a journey... We work hard, do great work and
                        ultimately make our brand partners happy.</p>
                    <p>With our years of experience in the field and our range of empowered client, we aim to get
                        clients the most innovative and multidimensional concepts, expressed through video, audio,
                        interactive and web, photography, graphic design and events.</p>
                </div>
            </div>
        </div>
    </div>
    <!-- approach  -->
    <div id="approach">
        <div class="row">
            <div class="col-md-6 text-center">
                <img src="{% static 'webapp/images/nescafe.png' %}" class="img-fluid" alt="">
            </div>
            <div class="col-md-6">
                <h2>OUR APPROACH</h2>
                <h3>01</h3><h5>Insight</h5>
                <p>We read the brief. We immerse ourselves in understanding the message we need to convey. We do
                    research and this is what informs the concept, drives the overarching and determines the medium
                    we will use.</p>
                <h3>02</h3><h5>Strategy</h5>
                <p>We establish the creative treatment and  expand on the primary medium, key emotive touchpoints,
                    media channels and extensions. Our commitment is to craft a full service of multi-media
                    solutions that works for the brand and the market.</p>
                <h3>03</h3><h5>Execution</h5>
                <p>Every project is defined by a single-minded message. The message is articulated through different
                    mediums and enforced by different partnerships.</p>
            </div>
        </div>
    </div>
    </div>


    <script src="{% static 'webapp/js/bootstrap.js' %}"></script>
{% endblock content %}

templates/webapp/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head profile="http://www.w3.org/2005/10/profile">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="icon"
      type="image/png"
      href="{% static 'webapp/images/logo.png' %}">
    <title>IMPACT INTERNATIONAL|{{ title }}</title>
    <link rel="stylesheet" href="{% static 'webapp/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'webapp/css/style.css' %}">
{#    <link rel="stylesheet" href="{% static 'webapp/css/fontawesome-all.css' %}">#}
</head>
<body class="container-fluid">
    <div class="mini-banner">
        {% include 'webapp/includes/navbar.html' %}
    </div>
    {% block content %}{% endblock %}
    {% include 'webapp/includes/footer.html' %}
    <script src="{% static 'webapp/js/bootstrap.js' %}"></script>
</body>
</html>

templates/webapp/contacts.html
{% extends 'webapp/base_layout.html' %}l>
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row" id="contacts-page">
        <div class="col-md-6">
            <h2>CONTACT US</h2>
            <h4>We'd love to hear from you...</h4>
            <address>
                P.O. BOX 44828 - 00100, NAIROBI, KENYA. <br/>
                TEL: <a href="tel:+254202097585">+254 202097585</a>, <a href="tel:+254208045040"> +254 208045040</a> <br/>
                MOBILE: <a href="tel:+254722564913">+254 722 564913</a>, <a href="tel:+254737564913">+254 737 564913</a>, <a
                    href="tel:+254722644213">+254 722 664231</a> <br/>
                E-MAIL: <a href="mailto:info@impacteastafrica.com">info@impacteastafrica.com</a> <br/>
                WEBSITE: <a href="www.impacteastafrica.com">www.impacteastafrica.com</a>
            </address>
        </div>
        <div class="col-md-6" style='background: url("{% static 'webapp/static/contactsbg.jpg' %}") center cover;'>
            <form>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" placeholder="Name">
                </div>
                <div class="form-group">
                    <textarea name="message" id="message" cols="62" rows="10" placeholder="Message"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Send</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/webapp/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="mx-auto my-2 order-0 order-md-0 position-relative">
{#        <a class="mx-auto" href="{% url 'webapp:home' %}">#}
{#            <img src="{% static 'images/logo.png' %}" class="rounded-circle">#}
{#        </a>#}
        <a href="{% url 'webapp:home' %}" class="navbar-brand">IMPACT INT'L</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 dual-collapse2 order-1 order-md-1"></div>
    <div class="navbar-collapse collapse w-100 dual-collapse2 order-2 order-md-2">
        <ul class="navbar-nav mr-auto text-right">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'webapp:home' %}">HOME</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:about' %}">ABOUT</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:contacts' %}">CONTACTS</a>
            </li>
        </ul>
    </div>
</nav>

templates/webapp/index.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head profile="http://www.w3.org/2005/10/profile">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="icon"
      type="image/png"
      href="{% static 'webapp/images/logo.png' %}">
    <title>IMPACT INTERNATIONAL|{{ title }}</title>
    <link rel="stylesheet" href="{% static 'webapp/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'webapp/css/style.css' %}">
{#    <link rel="stylesheet" href="{% static 'webapp/css/fontawesome-all.css' %}">#}
</head>
<body class="container-fluid">
    <!-- banner -->
    <div class="banner">
        {% include 'webapp/includes/navbar.html' %}
        <div class="col-md-6 intro">
            <h1>Idea-driven and result-oriented <br/> solutions that connect <br/> brands and
                experiences.</h1>
            <p>Our niche in event management, brand building, content creation, talent sourcing, branding and
                merchandising has etched our name in the communication industry.</p>
        </div>
        <div class="banner-btm">
            <div>
                <a href="#">GET IN TOUCH <span class="fa fa-long-arrow-alt-right"></span></a>
            </div>
            <div>
                <a href="#">EXPLORE <span class="fa fa-long-arrow-alt-right"></span></a>
            </div>
        </div>
    </div>
    <!-- about -->
    <div class="row about">
        <div class="col-sm-5"></div>
        <div class="col-sm-3">
            <p class="mini-header"> Why it matters</p>
            <h4 class="font-weight-bold">Great for clients, <br/>good for business</h4>
            <p>We help brands discover their true purpose. Combining strategic thinking, creativity and design to
                develop transformative ideas and distinctive brand identities.</p>
        </div>
    </div>
    <div class="clear"></div>
    <!-- approach -->
    <div class="container">
        <div class="row approach">
            <div class="col-md-6">
                <div>
                    <h3 class="font-weight-bold">A smart approach <br/>custom tailored to a firm's brand</h3>
                    <p>We believe that each event is unique, with its own objectives and challenges. It takes a real
                        partner to get to know your business, understand your objectives, and design and deliver an event
                        that will help you achieve your goals.</p>
                    <p>
                        <a href="#">LEARN MORE     <span class="fa fa-arrow-right"></span></a>
                    </p>
                </div>
            </div>
            <div class="col-md-6">
                <ol>
                    <li class="approach-list">
                        <div>
                            <p>Insight <span class="fa fa-arrow-right"></span></p>
                        </div>
                    </li>
                    <li class="approach-list">
                        <div>
                            <p>Strategy <span class="fa fa-arrow-right"></span></p>
                        </div>
                    </li>
                    <li class="approach-list">
                        <div>
                            <p>Execution <span class="fa fa-arrow-right"></span></p>
                        </div>
                    </li>
                </ol>
            </div>
        </div>
    </div>
    <!-- services -->
    <div class="pre-services"></div>
    <div class="services">
        <div class="row text-center">
            <div class="col-md-12">
                <h2>OUR SERVICES</h2>
            </div>
            <div class="col-md-6">
                <div>
                    <span class="fa fa-search"></span>
                    <h3>EVENTS</h3>
                    <p>We believe that each is unique, with its own objectives and challenges. It takes a real
                        partner to get to know your business, understand your objectives and design and deliver an
                        event that will help you achieve your goals.</p>
                </div>
                <div>
                    <span class="fa fa-rocket"></span>
                    <h3>CONTENT</h3>
                    <p>We believe that each is unique, with its own objectives and challenges. It takes a real
                        partner to get to know your business, understand your objectives and design and deliver an
                        event that will help you achieve your goals.</p>
                </div>
            </div>
            <div class="col-md-6">
                <div>
                    <span class="fa fa-bulb"></span>
                    <h3>BRANDING</h3>
                    <p>We help brands discover their true purpose. Combining strategic thinking, creativity and
                        design to develop transformative ideas and distinctive brand identities.</p>
                </div>
                <div>
                    <span class="fa fa-rocket"></span>
                    <h3>DIGITAL</h3>
                    <p>We find the place where the human and digital worlds intersect, exploring creative ways to
                        harness design and technology to help brands have more meaningful conversations.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="post-services">
        <div class="row">
            <div class="col-md-6"></div>
            <div class="col-md-6">
                <p>The Impact team is able to provide a full-service experience that includes:</p>
                <ul>
                    <li>Project administration and management</li>
                    <li>Event Branding and Marketing</li>
                    <li>Brand Building</li>
                    <li>Market Strategy</li>
                    <li>Script Writing</li>
                    <li>Social Media Management</li>
                    <li>Digital Media Buying</li>
                    <li>Events communication and promotion</li>
                    <li>Print production</li>
                    <li>Merchandising</li>
                    <li>Videography</li>
                    <li>Photography</li>
                    <li>Casting</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- clients -->
    <div id="clients">
        <div class="row">
            <div class="col-md-7"></div>
            <div class="col-md-5">
                <div>
                    <h2>OUR CLIENTS</h2>
                    <ul>
                        <li>TAC - The Advertising Company</li>
                        <li>Kenya Harlequin FC</li>
                        <li>Scanad</li>
                        <li>Ogilvy</li>
                        <li>Microsoft</li>
                        <li>Dream Catcher</li>
                        <li>NT Communications</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- contacts -->
    <div id="contacts">
        <div>
            <h2>CONTACT US</h2>
            <h4>We'd love to hear from you...</h4>
            <address>
                P.O. BOX 44828 - 00100, NAIROBI, KENYA. <br/>
                TEL: <a href="tel:+254202097585">+254 202097585</a>, <a href="tel:+254208045040"> +254 208045040</a> <br/>
                MOBILE: <a href="tel:+254722564913">+254 722 564913</a>, <a href="tel:+254737564913">+254 737 564913</a>, <a
                    href="tel:+254722644213">+254 722 664231</a> <br/>
                E-MAIL: <a href="mailto:info@impacteastafrica.com">info@impacteastafrica.com</a> <br/>
                WEBSITE: <a href="www.impacteastafrica.com">www.impacteastafrica.com</a>
            </address>
        </div>
    </div>
    {% include 'webapp/includes/footer.html' %}

    <script src="{% static 'webapp/js/bootstrap.js' %}"></script>
</body>
</html>

templates/webapp/philosophy.html
{% extends 'webapp/base_layout.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h3>OUR PHILOSOPHY</h3>
            <p>We aim to inspire generations and contribute to a sense of global community with products that
                captivate and educate.</p>
            <p>Our philosophy is simple; we take brands through a journey... we work hard, do great work and
                ultimately make our brand partners happy.</p>
            <p>With our years of experience in the field and our range of empowered talent, we aim to get our clients
                the most innovative and multidimensional concepts, expressed through video, audio, interactive and
                web, photography, graphic design and events.</p>
        </div>
        <div class="col-md-6"></div>
    </div>
{% endblock %}

webapp/templates/Webapp/about.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IMPACT INTERNATIONAL | ABOUT</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.css' %}">
</head>
<body class="container-fluid">
    <div class="mini-banner">
        {% include 'includes/navbar.html' %}
    </div>
    <div class="about">
        <div class="col-sm-3">
            <h3 class="font-weight-bold">ABOUT US</h3>
            <p>We are an idea driven and result oriented agency built to connect brands and experiences. Our niche in
                event management, brand building, content creation, talent sourcing, branding and merchandising has
                etched our name in the communication industry.</p>
        </div>
    </div>
    <div class="about-2">
        <div class="row">
            <div class="col-md-6">
                <div class="vsn-msn" id="vision">
                    <h3>Our Vision</h3>
                    <p>To be the leading promotion and positioning consultants within East Africa. To be acknowledged
                        for distinguished service to every client we encounter and every project we undertake.</p>
                </div>
                <div class="vsn-msn" id="mission">
                    <h3>Our Mission</h3>
                    <p>To provide our clients with quality services that improve their bottom line and increase their
                        brand worth.</p>
                </div>
            </div>
            <div class="col-md-6"></div>
        </div>
    </div>


    <script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

webapp/templates/Webapp/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IMPACT INTERNATIONAL</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.css' %}">
</head>
<body class="container-fluid">
    <div class="mini-banner">
        {% include 'includes/navbar.html' %}
    </div>
    {% block content %}{% endblock %}
    <script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

webapp/templates/Webapp/includes/navbar.html
    <div class="bg-dark" style="background-color: rgba(0,0,0,0.5);">
        <!--logo-->
       <div class="logo">
          <a href="/"><h1>IMPACT</h1></a>
       </div>
        <!--//logo-->
        <nav class="navbar navbar-default">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div id="navbar" class="navbar-collapse navbar-right collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">HOME</a></li>
                    <li><a href="{% url 'home' %}#about">ABOUT</a></li>
                    <li><a href="{% url 'home' %}#programs">PROGRAMS</a></li>
                    <li><a href="{% url 'home' %}#events">EVENTS</a></li>
                    <li><a href="{% url 'home' %}#team">TEAM</a></li>
{#                    <li><a href="{% url 'gallery' %}">GALLERY</a></li>#}
{#                    <li><a href="{% url 'contact' %}">CONTACT</a></li>#}
                </ul>
            </div>
        </nav>
    </div>

webapp/templates/Webapp/index.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IMPACT INTERNATIONAL</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.css' %}">
</head>
<body class="container-fluid">
    <!-- banner -->
    <div class="banner">
        {% include 'includes/navbar.html' %}
        <div class="col-md-6 intro">
            <h1>Idea-driven and result-oriented <br/> solutions that connect <br/> brands and
                experiences.</h1>
            <p>Our niche in event management, brand building, content creation, talent sourcing, branding and
                merchandising has etched our name in the communication industry.</p>
        </div>
        <div class="banner-btm">
            <div>
                <a href="#">GET IN TOUCH <span class="fa fa-long-arrow-alt-right"></span></a>
            </div>
            <div>
                <a href="#">EXPLORE <span class="fa fa-long-arrow-alt-right"></span></a>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <!-- about -->
    <div class="row about">
        <div class="col-sm-3">
            <p class="mini-header"> Why it matters</p>
            <h4 class="font-weight-bold">Great for clients, <br/>good for business</h4>
            <p>We help brands discover their true purpose. Combining strategic thinking, creativity and design to
                develop transformative ideas and distinctive brand identities.</p>
        </div>
    </div>
    <div class="clear"></div>
    <!-- approach -->
    <div class="container">
        <div class="row approach">
            <div class="col-md-6">
                <div>
                    <h3 class="font-weight-bold">A smart approach <br/>custom tailored to a firm's brand</h3>
                    <p>We believe that each event is unique, with its own objectives and challenges. It takes a real
                        partner to get to know your business, understand your objectives, and design and deliver an event
                        that will help you achieve your goals.</p>
                    <p>
                        <a href="#">LEARN MORE     <span class="fa fa-arrow-right"></span></a>
                    </p>
                </div>
            </div>
            <div class="col-md-6">
                <ol>
                    <li>
                        <div>
                            <p>Insight <span class="fa fa-arrow-right"></span></p>
                        </div>
                    </li>
                    <li>
                        <div>
                            <p>Strategy <span class="fa fa-arrow-right"></span></p>
                        </div>
                    </li>
                    <li>
                        <div>
                            <p>Execution <span class="fa fa-arrow-right"></span></p>
                        </div>
                    </li>
                </ol>
            </div>
        </div>
    </div>
    <!-- services -->
    <div class="services">
        <h2>OUR SERVICES</h2>
        <div class="row text-center">
            <div class="col-md-6">
                <div>
                    <span class="fa fa-search"></span>
                    <h3>EVENTS</h3>
                    <p>We believe that each is unique, with its own objectives and challenges. It takes a real
                        partner to get to know your business, understand your objectives and design and deliver an
                        event that will help you achieve your goals.</p>
                </div>
                <div>
                    <span class="fa fa-rocket"></span>
                    <h3>CONTENT</h3>
                    <p>We believe that each is unique, with its own objectives and challenges. It takes a real
                        partner to get to know your business, understand your objectives and design and deliver an
                        event that will help you achieve your goals.</p>
                </div>
            </div>
            <div class="col-md-6">
                <div>
                    <span class="fa fa-bulb"></span>
                    <h3>BRANDING</h3>
                    <p>We help brands discover their true purpose. Combining strategic thinking, creativity and
                        design to develop transformative ideas and distinctive brand identities.</p>
                </div>
                <div>
                    <span class="fa fa-rocket"></span>
                    <h3>DIGITAL</h3>
                    <p>We find the place where the human and digital worlds intersect, exploring creative ways to
                        harness design and technology to help brands have more meaningful conversations.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6"></div>
            <div class="col-md-6">
                <p>The Impact team is able to provide a full-service experience that includes:</p>
                <ul>
                    <li>Project administration and management</li>
                    <li>Event Branding and Marketing</li>
                    <li>Brand Building</li>
                    <li>Market Strategy</li>
                    <li>Script Writing</li>
                    <li>Social Media Management</li>
                    <li>Digital Media Buying</li>
                    <li>Events communication and promotion</li>
                    <li>Print production</li>
                    <li>Merchandising</li>
                    <li>Videography</li>
                    <li>Photography</li>
                    <li>Casting</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- philosophy -->
    <div class="philosophy">
        <div class="row">
            <div class="col-md-push-6 col-md-6"></div>
            <div class="col-md-pull-6 col-md-6">
                <div>
                    <h2>OUR PHILOSOPHY</h2>
                    <p>We aim to inspire generations and contribute to a sense of global community with products
                        that captivate and educate.</p>
                    <p>Our philosophy is simple: we take brands through a journey... We work hard, do great work and
                        ultimately make our brand partners happy.</p>
                    <p>With our years of experience in the field and our range of empowered client, we aim to get
                        clients the most innovative and multidimensional concepts, expressed through video, audio,
                        interactive and web, photography, graphic design and events.</p>
                </div>
            </div>
        </div>
    </div>
    <!-- approach  -->
    <div id="approach">
        <h2>OUR APPROACH</h2>
        <div class="row">
            <div class="col-md-6"></div>
            <div class="col-md-6">
                <h3>01</h3><h5>Insight</h5>
                <p>We read the brief. We immerse ourselves in understanding the message we need to convey. We do
                    research and this is what informs the concept, drives the overarching and determines the medium
                    we will use.</p>
                <h3>02</h3><h5>Strategy</h5>
                <p>We establish the creative treatment and  expand on the primary medium, key emotive touchpoints,
                    media channels and extensions. Our commitment is to craft a full service of multi-media
                    solutions that works for the brand and the market.</p>
                <h3>03</h3><h5>Execution</h5>
                <p>Every project is defined by a single-minded message. The message is articulated through different
                    mediums and enforced by different partnerships.</p>
            </div>
        </div>
    </div>
    <!-- clients -->
    <div id="clients">
        <h2>OUR CLIENTS</h2>
    </div>
    <!-- contacts -->
    <div id="clients">
        <h2>CONTACT US</h2>
        <h4>We'd love to hear from you...</h4>
        <address>
            P.O. BOX 44828 - 00100, NAIROBI, KENYA. <br/>
            TEL: <a href="tel:+254202097585">+254 202097585</a>, <a href="tel:+254208045040"> +254 208045040</a> <br/>
            MOBILE: <a href="tel:+254722564913">+254 722 564913</a>, <a href="tel:+254737564913">+254 737 564913</a>, <a
                href="tel:+254722644213">+254 722 664231</a> <br/>
            E-MAIL: <a href="mailto:info@impacteastafrica.com">info@impacteastafrica.com</a> <br/>
            WEBSITE: <a href="www.impacteastafrica.com">www.impacteastafrica.com</a>
        </address>
    </div>
    {% include 'includes/footer.html' %}

    <script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>